sudo: required
language: generic

services:
  - docker

env:
  - NAME=elasticsearch TAGS="livingdocs/elasticsearch:latest livingdocs/elasticsearch:5 livingdocs/elasticsearch:5.6 livingdocs/elasticsearch:5.6.7"

script:
  - docker build -t $NAME .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      for tag in $TAGS; do
        docker tag $NAME $tag;
        echo "push the image $tag";
        docker push $tag 1>/dev/null;
        echo "successfully pushed the image $tag";
      done
    fi
